// 引路人 Lumora · 前端常數資料

window.LUMORA_DATA = {
  countries: [
    { code: "TW", name: "台灣", provinces: [
      { name: "台北", lng: 121.5 },
      { name: "新北", lng: 121.4 },
      { name: "桃園", lng: 121.3 },
      { name: "新竹", lng: 121.0 },
      { name: "苗栗", lng: 120.8 },
      { name: "台中", lng: 120.7 },
      { name: "彰化", lng: 120.5 },
      { name: "南投", lng: 120.7 },
      { name: "雲林", lng: 120.5 },
      { name: "嘉義", lng: 120.4 },
      { name: "台南", lng: 120.2 },
      { name: "高雄", lng: 120.3 },
      { name: "屏東", lng: 120.5 },
      { name: "宜蘭", lng: 121.7 },
      { name: "花蓮", lng: 121.6 },
      { name: "台東", lng: 121.1 },
      { name: "澎湖", lng: 119.6 },
      { name: "金門", lng: 118.3 },
      { name: "馬祖", lng: 119.9 },
      { name: "基隆", lng: 121.7 },
    ]},
    { code: "CN", name: "中國大陸", provinces: [
      { name: "北京", lng: 116.4 },
      { name: "上海", lng: 121.5 },
      { name: "天津", lng: 117.2 },
      { name: "重慶", lng: 106.5 },
      { name: "河北（石家莊）", lng: 114.5 },
      { name: "山西（太原）", lng: 112.5 },
      { name: "遼寧（瀋陽）", lng: 123.4 },
      { name: "吉林（長春）", lng: 125.3 },
      { name: "黑龍江（哈爾濱）", lng: 126.6 },
      { name: "江蘇（南京）", lng: 118.8 },
      { name: "浙江（杭州）", lng: 120.2 },
      { name: "安徽（合肥）", lng: 117.3 },
      { name: "福建（福州）", lng: 119.3 },
      { name: "江西（南昌）", lng: 115.9 },
      { name: "山東（濟南）", lng: 117.0 },
      { name: "河南（鄭州）", lng: 113.6 },
      { name: "湖北（武漢）", lng: 114.3 },
      { name: "湖南（長沙）", lng: 112.9 },
      { name: "廣東（廣州）", lng: 113.3 },
      { name: "廣西（南寧）", lng: 108.4 },
      { name: "海南（海口）", lng: 110.3 },
      { name: "四川（成都）", lng: 104.1 },
      { name: "貴州（貴陽）", lng: 106.7 },
      { name: "雲南（昆明）", lng: 102.7 },
      { name: "西藏（拉薩）", lng: 91.1 },
      { name: "陝西（西安）", lng: 108.9 },
      { name: "甘肅（蘭州）", lng: 103.8 },
      { name: "青海（西寧）", lng: 101.8 },
      { name: "寧夏（銀川）", lng: 106.3 },
      { name: "新疆（烏魯木齊）", lng: 87.6 },
      { name: "內蒙古（呼和浩特）", lng: 111.7 },
      { name: "香港", lng: 114.2 },
      { name: "澳門", lng: 113.5 },
    ]},
    { code: "JP", name: "日本", provinces: [
      { name: "北海道", lng: 141.4 },
      { name: "青森", lng: 140.7 },
      { name: "岩手", lng: 141.2 },
      { name: "宮城", lng: 140.9 },
      { name: "秋田", lng: 140.1 },
      { name: "山形", lng: 140.4 },
      { name: "福島", lng: 140.5 },
      { name: "茨城", lng: 140.5 },
      { name: "栃木", lng: 139.9 },
      { name: "群馬", lng: 139.1 },
      { name: "埼玉", lng: 139.6 },
      { name: "千葉", lng: 140.1 },
      { name: "東京", lng: 139.7 },
      { name: "神奈川", lng: 139.6 },
      { name: "新潟", lng: 139.1 },
      { name: "富山", lng: 137.2 },
      { name: "石川", lng: 136.6 },
      { name: "福井", lng: 136.2 },
      { name: "山梨", lng: 138.6 },
      { name: "長野", lng: 137.9 },
      { name: "岐阜", lng: 136.7 },
      { name: "靜岡", lng: 138.4 },
      { name: "愛知", lng: 136.9 },
      { name: "三重", lng: 136.5 },
      { name: "滋賀", lng: 136.0 },
      { name: "京都", lng: 135.8 },
      { name: "大阪", lng: 135.5 },
      { name: "兵庫", lng: 135.2 },
      { name: "奈良", lng: 135.8 },
      { name: "和歌山", lng: 135.2 },
      { name: "鳥取", lng: 134.2 },
      { name: "島根", lng: 132.6 },
      { name: "岡山", lng: 133.9 },
      { name: "廣島", lng: 132.5 },
      { name: "山口", lng: 131.5 },
      { name: "德島", lng: 134.6 },
      { name: "香川", lng: 134.1 },
      { name: "愛媛", lng: 132.8 },
      { name: "高知", lng: 133.6 },
      { name: "福岡", lng: 130.4 },
      { name: "佐賀", lng: 130.3 },
      { name: "長崎", lng: 129.9 },
      { name: "熊本", lng: 130.7 },
      { name: "大分", lng: 131.6 },
      { name: "宮崎", lng: 131.4 },
      { name: "鹿兒島", lng: 130.6 },
      { name: "沖繩", lng: 127.7 },
    ]},
    { code: "KR", name: "韓國", provinces: [
      { name: "首爾", lng: 127.0 },
      { name: "釜山", lng: 129.0 },
      { name: "大邱", lng: 128.6 },
      { name: "仁川", lng: 126.7 },
      { name: "光州", lng: 126.9 },
      { name: "大田", lng: 127.4 },
      { name: "蔚山", lng: 129.3 },
      { name: "世宗", lng: 127.3 },
      { name: "京畿道（水原）", lng: 127.0 },
      { name: "江原道（春川）", lng: 127.7 },
      { name: "忠清北道（清州）", lng: 127.5 },
      { name: "忠清南道（天安）", lng: 127.2 },
      { name: "全羅北道（全州）", lng: 127.2 },
      { name: "全羅南道（光陽）", lng: 127.7 },
      { name: "慶尚北道（大邱）", lng: 128.6 },
      { name: "慶尚南道（昌原）", lng: 128.7 },
      { name: "濟州島", lng: 126.5 },
    ]},
    { code: "US", name: "美國", provinces: [
      { name: "阿拉巴馬", lng: -86.8 },
      { name: "阿拉斯加", lng: -149.9 },
      { name: "亞利桑那", lng: -112.1 },
      { name: "阿肯色", lng: -92.4 },
      { name: "加利福尼亞（洛杉磯）", lng: -118.2 },
      { name: "科羅拉多", lng: -104.9 },
      { name: "康乃狄克", lng: -72.7 },
      { name: "德拉瓦", lng: -75.5 },
      { name: "佛羅里達", lng: -81.5 },
      { name: "喬治亞（亞特蘭大）", lng: -84.4 },
      { name: "夏威夷", lng: -157.8 },
      { name: "愛達荷", lng: -116.2 },
      { name: "伊利諾州", lng: -89.7 },
      { name: "印第安納", lng: -86.2 },
      { name: "愛荷華", lng: -93.6 },
      { name: "堪薩斯", lng: -95.7 },
      { name: "肯塔基", lng: -84.9 },
      { name: "路易斯安那", lng: -91.1 },
      { name: "緬因州", lng: -69.8 },
      { name: "馬里蘭", lng: -76.5 },
      { name: "麻薩諸塞", lng: -71.1 },
      { name: "密西根", lng: -84.6 },
      { name: "明尼蘇達", lng: -93.1 },
      { name: "密西西比", lng: -90.2 },
      { name: "密蘇里", lng: -92.2 },
      { name: "蒙大拿", lng: -110.4 },
      { name: "內布拉斯加", lng: -96.7 },
      { name: "內華達", lng: -119.8 },
      { name: "新罕布什爾", lng: -71.5 },
      { name: "紐澤西", lng: -74.7 },
      { name: "新墨西哥", lng: -106.7 },
      { name: "紐約州", lng: -74.0 },
      { name: "北卡羅來納", lng: -79.1 },
      { name: "北達科他", lng: -100.8 },
      { name: "俄亥俄", lng: -82.9 },
      { name: "奧克拉荷馬", lng: -97.5 },
      { name: "奧勒岡", lng: -122.7 },
      { name: "賓夕法尼亞", lng: -77.2 },
      { name: "羅德島", lng: -71.4 },
      { name: "南卡羅來納", lng: -81.1 },
      { name: "南達科他", lng: -100.3 },
      { name: "田納西", lng: -86.8 },
      { name: "德克薩斯", lng: -97.4 },
      { name: "猶他", lng: -111.9 },
      { name: "佛蒙特", lng: -72.6 },
      { name: "維吉尼亞", lng: -77.5 },
      { name: "華盛頓州", lng: -122.3 },
      { name: "西維吉尼亞", lng: -81.6 },
      { name: "威斯康辛", lng: -89.4 },
      { name: "懷俄明", lng: -107.3 },
      { name: "華盛頓特區", lng: -77.0 },
    ]},
    { code: "CA", name: "加拿大", provinces: [
      { name: "不列顛哥倫比亞", lng: -123.1 },
      { name: "亞伯達", lng: -114.1 },
      { name: "薩克其萬", lng: -106.7 },
      { name: "馬尼托巴", lng: -97.1 },
      { name: "安大略（多倫多）", lng: -79.4 },
      { name: "魁北克（蒙特婁）", lng: -73.6 },
      { name: "新伯倫瑞克", lng: -66.7 },
      { name: "新斯科舍", lng: -63.6 },
      { name: "愛德華王子島", lng: -63.1 },
      { name: "紐芬蘭", lng: -52.7 },
      { name: "育空", lng: -135.1 },
      { name: "西北地區", lng: -114.5 },
      { name: "努納武特", lng: -83.1 },
    ]},
    { code: "AU", name: "澳大利亞", provinces: [
      { name: "新南威爾斯（雪梨）", lng: 151.2 },
      { name: "維多利亞（墨爾本）", lng: 144.9 },
      { name: "昆士蘭（布里斯本）", lng: 153.0 },
      { name: "西澳（伯斯）", lng: 115.9 },
      { name: "南澳（阿得雷德）", lng: 138.6 },
      { name: "塔斯馬尼亞（荷巴特）", lng: 147.3 },
      { name: "首都直轄區（坎培拉）", lng: 149.1 },
      { name: "北領地（達爾文）", lng: 130.8 },
    ]},
    { code: "IN", name: "印度", provinces: [
      { name: "新德里（首都直轄區）", lng: 77.2 },
      { name: "安得拉邦（海德拉巴）", lng: 78.5 },
      { name: "阿薩姆（古瓦哈提）", lng: 91.7 },
      { name: "比哈爾（巴特那）", lng: 85.1 },
      { name: "恰蒂斯加爾（賴浦爾）", lng: 81.6 },
      { name: "果阿（帕納吉）", lng: 73.8 },
      { name: "古吉拉特（甘地訥格爾）", lng: 72.7 },
      { name: "哈里亞納（昌迪加爾）", lng: 76.8 },
      { name: "喜馬偕爾（西姆拉）", lng: 77.2 },
      { name: "賈坎德（蘭契）", lng: 85.3 },
      { name: "卡納塔克（班加羅爾）", lng: 77.6 },
      { name: "喀拉拉（提里凡得琅）", lng: 76.9 },
      { name: "中央邦（博帕爾）", lng: 77.4 },
      { name: "馬哈拉什特拉（孟買）", lng: 72.9 },
      { name: "曼尼普爾（因帕爾）", lng: 93.9 },
      { name: "梅加拉亞（西隆）", lng: 91.9 },
      { name: "米佐拉姆（艾藻爾）", lng: 92.7 },
      { name: "那加蘭（科希馬）", lng: 94.1 },
      { name: "奧里薩（帕特納伊克）", lng: 85.8 },
      { name: "旁遮普（昌迪加爾）", lng: 76.8 },
      { name: "拉賈斯坦（齋浦爾）", lng: 75.8 },
      { name: "錫金（甘托克）", lng: 88.5 },
      { name: "泰米爾納德（清奈）", lng: 80.3 },
      { name: "特倫甘納（海德拉巴）", lng: 78.5 },
      { name: "特里普拉（阿加爾塔拉）", lng: 91.3 },
      { name: "北方邦（勒克瑙）", lng: 81.0 },
      { name: "北阿坎德（德拉敦）", lng: 78.0 },
      { name: "西孟加拉（加爾各答）", lng: 88.4 },
      { name: "查謨和喀什米爾（斯利那加爾）", lng: 74.8 },
      { name: "拉達克（列城）", lng: 77.6 },
    ]},
    { code: "BR", name: "巴西", provinces: [
      { name: "阿克里（黑布蘭卡）", lng: -67.8 },
      { name: "阿拉戈斯（馬塞約）", lng: -35.7 },
      { name: "阿馬帕（馬卡帕）", lng: -51.1 },
      { name: "亞馬遜（馬瑙斯）", lng: -60.0 },
      { name: "巴伊亞（薩爾瓦多）", lng: -38.5 },
      { name: "塞阿拉（福塔雷薩）", lng: -38.5 },
      { name: "聯邦直轄區（巴西利亞）", lng: -47.9 },
      { name: "聖埃斯皮里托（維多利亞）", lng: -40.3 },
      { name: "戈亞斯（戈亞尼亞）", lng: -49.3 },
      { name: "馬拉尼昂（聖路易斯）", lng: -44.3 },
      { name: "馬托格羅索（庫亞巴）", lng: -56.1 },
      { name: "南馬托格羅索（坎普格蘭德）", lng: -54.6 },
      { name: "米納斯吉拉斯（貝洛奧里藏特）", lng: -44.0 },
      { name: "帕拉（貝倫）", lng: -48.5 },
      { name: "帕拉伊巴（若昂佩索阿）", lng: -34.9 },
      { name: "巴拉納（庫里提巴）", lng: -49.3 },
      { name: "伯南布科（累西腓）", lng: -34.9 },
      { name: "皮奧伊（帝雷希納）", lng: -42.8 },
      { name: "里約熱內盧（里約）", lng: -43.2 },
      { name: "北里約格蘭德（納塔爾）", lng: -35.2 },
      { name: "南里約格蘭德（阿雷格里港）", lng: -51.2 },
      { name: "朗多尼亞（韋柳港）", lng: -63.9 },
      { name: "羅賴馬（博阿維斯塔）", lng: -60.7 },
      { name: "聖卡塔琳娜（弗洛里亞諾波利斯）", lng: -48.5 },
      { name: "聖保羅", lng: -46.6 },
      { name: "塞爾希培（阿拉卡茹）", lng: -37.1 },
      { name: "托坎廷斯（帕爾馬斯）", lng: -48.4 },
    ]},
    { code: "RU", name: "俄羅斯", provinces: [
      { name: "莫斯科", lng: 37.6 },
      { name: "聖彼得堡", lng: 30.3 },
      { name: "新西伯利亞（新西伯利亞州）", lng: 82.9 },
      { name: "葉卡捷琳堡（斯維爾德洛夫斯克州）", lng: 60.6 },
      { name: "下諾夫哥羅德", lng: 44.0 },
      { name: "喀山（韃靼斯坦共和國）", lng: 49.1 },
      { name: "薩馬拉", lng: 50.2 },
      { name: "烏法（巴什科爾托斯坦）", lng: 55.9 },
      { name: "羅斯托夫那頓（羅斯托夫州）", lng: 39.7 },
      { name: "伏爾加格勒", lng: 44.5 },
      { name: "克拉斯諾達爾", lng: 38.9 },
      { name: "沃羅涅日", lng: 39.2 },
      { name: "薩拉托夫", lng: 46.0 },
      { name: "秋明（秋明州）", lng: 68.9 },
      { name: "托木斯克", lng: 84.9 },
      { name: "伊爾庫茨克", lng: 104.3 },
      { name: "哈巴羅夫斯克", lng: 135.1 },
      { name: "海參崴（濱海邊疆區）", lng: 132.0 },
      { name: "克拉斯諾亞爾斯克", lng: 92.8 },
      { name: "雅庫茨克（薩哈共和國）", lng: 129.7 },
      { name: "摩爾曼斯克", lng: 33.1 },
      { name: "阿爾漢格爾斯克", lng: 40.5 },
      { name: "車里雅賓斯克", lng: 61.4 },
      { name: "彼爾姆", lng: 56.2 },
    ]},
    { code: "DE", name: "德國", provinces: [
      { name: "巴登-符騰堡（斯圖加特）", lng: 9.2 },
      { name: "巴伐利亞（慕尼黑）", lng: 11.6 },
      { name: "柏林", lng: 13.4 },
      { name: "布蘭登堡（波茨坦）", lng: 13.1 },
      { name: "不萊梅", lng: 8.8 },
      { name: "漢堡", lng: 10.0 },
      { name: "黑森（法蘭克福）", lng: 8.7 },
      { name: "梅克倫堡-前波美拉尼亞（什未林）", lng: 11.4 },
      { name: "下薩克森（漢諾威）", lng: 9.7 },
      { name: "北萊茵-西伐利亞（杜塞道夫）", lng: 6.8 },
      { name: "萊茵蘭-普法爾茨（美因茨）", lng: 8.3 },
      { name: "薩爾（薩爾布呂肯）", lng: 7.0 },
      { name: "薩克森（德勒斯登）", lng: 13.7 },
      { name: "薩克森-安哈特（馬格德堡）", lng: 11.6 },
      { name: "石勒蘇益格-霍爾斯泰因（基爾）", lng: 10.1 },
      { name: "圖林根（愛爾福特）", lng: 11.0 },
    ]},
    { code: "GB", name: "英國", provinces: [
      { name: "大倫敦", lng: -0.1 },
      { name: "英格蘭東南（布萊頓）", lng: -0.1 },
      { name: "英格蘭西南（布里斯托）", lng: -2.6 },
      { name: "英格蘭東部（劍橋）", lng: 0.1 },
      { name: "英格蘭東中部（諾丁漢）", lng: -1.2 },
      { name: "英格蘭西中部（伯明罕）", lng: -1.9 },
      { name: "英格蘭西北（曼徹斯特）", lng: -2.2 },
      { name: "英格蘭約克夏（里茲）", lng: -1.5 },
      { name: "英格蘭東北（紐卡斯爾）", lng: -1.6 },
      { name: "蘇格蘭（愛丁堡）", lng: -3.2 },
      { name: "威爾斯（卡地夫）", lng: -3.2 },
      { name: "北愛爾蘭（貝爾法斯特）", lng: -6.0 },
    ]},
    { code: "FR", name: "法國", provinces: [
      { name: "法蘭西島（巴黎）", lng: 2.3 },
      { name: "奧克西塔尼亞（土魯斯）", lng: 1.4 },
      { name: "新阿基坦（波爾多）", lng: -0.6 },
      { name: "奧弗涅-隆河-阿爾卑斯（里昂）", lng: 4.8 },
      { name: "普羅旺斯-阿爾卑斯-蔚藍海岸（馬賽）", lng: 5.4 },
      { name: "大東部（史特拉斯堡）", lng: 7.7 },
      { name: "上法蘭西（里爾）", lng: 3.1 },
      { name: "諾曼第（盧昂）", lng: 1.1 },
      { name: "布列塔尼（雷恩）", lng: -1.7 },
      { name: "中央-羅亞爾河谷（奧爾良）", lng: 1.9 },
      { name: "勃艮第-弗朗什孔泰（第戎）", lng: 5.0 },
      { name: "盧瓦爾河地區（南特）", lng: -1.6 },
      { name: "科西嘉（阿雅克肖）", lng: 8.7 },
    ]},
    { code: "IT", name: "義大利", provinces: [
      { name: "拉齊奧（羅馬）", lng: 12.5 },
      { name: "倫巴底（米蘭）", lng: 9.2 },
      { name: "坎帕尼亞（那不勒斯）", lng: 14.3 },
      { name: "西西里（巴勒摩）", lng: 13.4 },
      { name: "威尼托（威尼斯）", lng: 12.3 },
      { name: "皮埃蒙特（都靈）", lng: 7.7 },
      { name: "艾米利亞-羅馬涅（波隆那）", lng: 11.3 },
      { name: "托斯卡納（佛羅倫斯）", lng: 11.3 },
      { name: "普利亞（巴里）", lng: 16.9 },
      { name: "卡拉布里亞（卡坦扎羅）", lng: 16.6 },
      { name: "薩丁尼亞（卡利亞里）", lng: 9.1 },
      { name: "利古里亞（熱那亞）", lng: 8.9 },
      { name: "馬爾凱（安科納）", lng: 13.5 },
      { name: "阿布魯佐（拉奎拉）", lng: 13.4 },
      { name: "弗留利-威尼斯朱利亞（的里雅斯特）", lng: 13.8 },
      { name: "翁布里亞（佩魯賈）", lng: 12.4 },
      { name: "巴西利卡塔（波滕察）", lng: 15.8 },
      { name: "莫利塞（坎波巴索）", lng: 14.7 },
      { name: "特倫蒂諾-上阿迪傑（特倫托）", lng: 11.1 },
      { name: "瓦萊達奧斯塔（奧斯塔）", lng: 7.3 },
    ]},
    { code: "ES", name: "西班牙", provinces: [
      { name: "馬德里", lng: -3.7 },
      { name: "加泰隆尼亞（巴塞隆納）", lng: 2.2 },
      { name: "安達盧西亞（塞維亞）", lng: -5.9 },
      { name: "瓦倫西亞", lng: -0.4 },
      { name: "加利西亞（聖地亞哥德孔波斯特拉）", lng: -8.5 },
      { name: "卡斯提亞-拉曼恰（托雷多）", lng: -4.0 },
      { name: "卡斯提亞和萊昂（瓦利亞多利德）", lng: -4.7 },
      { name: "巴斯克（畢爾包）", lng: -2.9 },
      { name: "加那利群島（拉斯帕爾馬斯）", lng: -15.4 },
      { name: "阿拉貢（薩拉戈薩）", lng: -0.9 },
      { name: "阿斯圖里亞斯（奧維耶多）", lng: -5.8 },
      { name: "艾斯特雷馬杜拉（梅里達）", lng: -6.3 },
      { name: "穆爾西亞", lng: -1.1 },
      { name: "納瓦拉（潘普洛納）", lng: -1.6 },
      { name: "坎塔布里亞（桑坦德爾）", lng: -3.8 },
      { name: "里奧哈（洛格羅尼奧）", lng: -2.4 },
      { name: "巴利亞利群島（帕爾馬）", lng: 2.7 },
    ]},
    { code: "MX", name: "墨西哥", provinces: [
      { name: "墨西哥城", lng: -99.1 },
      { name: "哈利斯科（瓜達拉哈拉）", lng: -103.3 },
      { name: "新萊昂（蒙特雷）", lng: -100.3 },
      { name: "普埃布拉", lng: -98.2 },
      { name: "瓜納華托", lng: -101.2 },
      { name: "韋拉克魯斯", lng: -96.1 },
      { name: "奇瓦瓦", lng: -106.1 },
      { name: "米卻肯", lng: -101.2 },
      { name: "塔毛利帕斯（雷諾薩）", lng: -98.3 },
      { name: "巴哈加利福尼亞（蒂華納）", lng: -117.0 },
      { name: "索諾拉（埃莫西約）", lng: -110.9 },
      { name: "科阿韋拉（薩爾蒂約）", lng: -101.0 },
      { name: "下加利福尼亞蘇爾", lng: -110.3 },
      { name: "錫那羅亞（庫利亞坎）", lng: -107.4 },
      { name: "奧哈卡（瓦哈卡）", lng: -96.7 },
      { name: "恰帕斯（圖斯特拉古鐵雷斯）", lng: -93.1 },
      { name: "坎佩切", lng: -90.5 },
      { name: "克雷塔羅", lng: -100.4 },
      { name: "塔巴斯科（比亞埃爾莫薩）", lng: -92.9 },
      { name: "莫雷洛斯（庫埃納瓦卡）", lng: -99.2 },
      { name: "伊達爾戈（帕丘卡）", lng: -98.7 },
      { name: "格雷羅（阿卡普爾科）", lng: -99.9 },
      { name: "杜蘭戈", lng: -104.7 },
      { name: "薩卡特卡斯", lng: -102.6 },
      { name: "科利馬", lng: -103.7 },
      { name: "阿瓜斯卡連特斯", lng: -102.3 },
      { name: "納亞里特（特皮克）", lng: -104.9 },
      { name: "特拉斯卡拉", lng: -98.2 },
      { name: "尤卡坦（梅里達）", lng: -89.6 },
      { name: "金塔納羅奧（坎昆）", lng: -86.9 },
      { name: "聖路易斯波托西", lng: -101.0 },
      { name: "墨西哥州（托盧卡）", lng: -99.7 },
    ]},
    { code: "AR", name: "阿根廷", provinces: [
      { name: "布宜諾斯艾利斯", lng: -58.4 },
      { name: "科爾多瓦", lng: -64.2 },
      { name: "羅薩里奧（聖菲）", lng: -60.7 },
      { name: "門多薩", lng: -68.8 },
      { name: "圖庫曼", lng: -65.2 },
      { name: "薩爾塔", lng: -65.4 },
      { name: "聖地亞哥德爾埃斯特羅", lng: -64.3 },
      { name: "科連特斯", lng: -58.8 },
      { name: "巴塔哥尼亞（科馬胡伊達）", lng: -70.0 },
      { name: "火地島（烏斯懷亞）", lng: -68.3 },
    ]},
    { code: "CL", name: "智利", provinces: [
      { name: "聖地亞哥", lng: -70.7 },
      { name: "瓦爾帕萊索", lng: -71.6 },
      { name: "比奧比奧（康塞普西翁）", lng: -73.1 },
      { name: "安托法加斯塔", lng: -70.4 },
      { name: "阿里卡（阿里卡和帕里納科塔）", lng: -70.3 },
      { name: "阿勞卡尼亞（特木科）", lng: -72.6 },
      { name: "馬加雷納斯（蓬塔阿雷納斯）", lng: -70.9 },
    ]},
    { code: "CO", name: "哥倫比亞", provinces: [
      { name: "波哥大", lng: -74.1 },
      { name: "麥德林（安蒂奧基亞）", lng: -75.6 },
      { name: "卡利（瓦耶德卡烏卡）", lng: -76.5 },
      { name: "巴蘭基亞（大西洋）", lng: -74.8 },
      { name: "卡塔赫納（玻利瓦爾）", lng: -75.5 },
      { name: "布卡拉曼加（桑坦德爾）", lng: -73.1 },
    ]},
    { code: "PE", name: "秘魯", provinces: [
      { name: "利馬", lng: -77.0 },
      { name: "阿雷基帕", lng: -71.5 },
      { name: "特魯希略（拉利伯塔德）", lng: -79.0 },
      { name: "奇克拉約（蘭巴耶克）", lng: -79.8 },
      { name: "庫斯科", lng: -72.0 },
      { name: "伊基托斯（洛雷托）", lng: -73.2 },
    ]},
    { code: "SG", name: "新加坡", provinces: [{ name: "新加坡", lng: 103.8 }] },
    { code: "MY", name: "馬來西亞", provinces: [
      { name: "吉隆坡", lng: 101.7 },
      { name: "檳城", lng: 100.3 },
      { name: "新山", lng: 103.8 },
      { name: "古晉（沙撈越）", lng: 110.3 },
      { name: "哥打基納巴盧（沙巴）", lng: 116.1 },
    ]},
    { code: "TH", name: "泰國", provinces: [
      { name: "曼谷", lng: 100.5 },
      { name: "清邁", lng: 99.0 },
      { name: "普吉", lng: 98.4 },
      { name: "呵叻（孔敬）", lng: 102.8 },
      { name: "帕塔亞（春武里）", lng: 100.9 },
    ]},
    { code: "VN", name: "越南", provinces: [
      { name: "河內", lng: 105.8 },
      { name: "胡志明市", lng: 106.7 },
      { name: "峴港", lng: 108.2 },
      { name: "海防", lng: 106.7 },
      { name: "芹苴", lng: 105.8 },
      { name: "順化", lng: 107.6 },
      { name: "廣寧（下龍灣）", lng: 107.1 },
      { name: "奈壯（慶和）", lng: 109.2 },
    ]},
    { code: "ID", name: "印尼", provinces: [
      { name: "爪哇（雅加達）", lng: 106.8 },
      { name: "峇里", lng: 115.2 },
      { name: "蘇門答臘（棉蘭）", lng: 98.7 },
      { name: "加里曼丹（婆羅洲）（巴里巴板）", lng: 116.8 },
      { name: "蘇拉威西（望加錫）", lng: 119.4 },
      { name: "巴布亞（查亞普拉）", lng: 140.7 },
    ]},
    { code: "PH", name: "菲律賓", provinces: [
      { name: "國家首都區（馬尼拉）", lng: 121.0 },
      { name: "科迪勒拉行政區（碧瑤）", lng: 120.6 },
      { name: "伊羅戈斯（維甘）", lng: 120.4 },
      { name: "卡加延河谷（圖格加勞）", lng: 121.7 },
      { name: "中呂宋（班邦加）", lng: 120.7 },
      { name: "卡拉巴松（甲米地）", lng: 120.9 },
      { name: "米馬羅帕（奧羅拉）", lng: 121.9 },
      { name: "比科爾（黎牙實比）", lng: 123.7 },
      { name: "西維薩亞斯（伊洛伊洛）", lng: 122.6 },
      { name: "中維薩亞斯（宿霧）", lng: 123.9 },
      { name: "東維薩亞斯（塔克洛班）", lng: 125.0 },
      { name: "三寶顏半島（三寶顏）", lng: 123.9 },
      { name: "北民答那峨（卡加延德奧羅）", lng: 124.7 },
      { name: "達沃（達沃市）", lng: 125.6 },
      { name: "索科薩根（哥打巴托）", lng: 124.8 },
      { name: "卡拉加（蘇里高）", lng: 125.5 },
      { name: "邦薩摩諾（馬拉維）", lng: 124.3 },
    ]},
    { code: "SA", name: "沙烏地阿拉伯", provinces: [
      { name: "利雅德", lng: 46.7 },
      { name: "吉達（麥加省）", lng: 39.2 },
      { name: "麥加", lng: 39.8 },
      { name: "麥地那", lng: 39.6 },
      { name: "達曼（東部省）", lng: 50.1 },
      { name: "塔布克", lng: 36.6 },
      { name: "阿布哈（阿西爾省）", lng: 42.5 },
      { name: "納季蘭", lng: 44.1 },
      { name: "哈伊勒", lng: 41.7 },
      { name: "焦夫", lng: 40.1 },
      { name: "巴哈", lng: 41.5 },
      { name: "北部邊界（阿拉爾）", lng: 41.0 },
      { name: "賈贊", lng: 42.6 },
    ]},
    { code: "AE", name: "阿聯酋", provinces: [
      { name: "杜拜", lng: 55.3 },
      { name: "阿布達比", lng: 54.4 },
      { name: "夏爾迦", lng: 55.4 },
      { name: "阿吉曼", lng: 55.5 },
      { name: "烏姆蓋萬", lng: 55.6 },
      { name: "哈伊馬角", lng: 55.8 },
      { name: "富查伊拉", lng: 56.3 },
    ]},
    { code: "ZA", name: "南非", provinces: [
      { name: "豪登（約翰尼斯堡）", lng: 28.0 },
      { name: "西開普（開普敦）", lng: 18.4 },
      { name: "誇祖魯-納塔爾（德班）", lng: 31.0 },
      { name: "東開普（伊麗莎白港）", lng: 25.6 },
      { name: "林波波（波羅瓜內）", lng: 29.5 },
      { name: "普馬蘭加（內爾斯普雷特）", lng: 30.9 },
      { name: "自由州（布隆方丹）", lng: 26.2 },
      { name: "北開普（金伯利）", lng: 24.8 },
      { name: "西北（魯斯滕堡）", lng: 27.2 },
    ]},
    { code: "EG", name: "埃及", provinces: [
      { name: "開羅", lng: 31.2 },
      { name: "亞歷山大", lng: 29.9 },
      { name: "吉薩", lng: 31.2 },
      { name: "盧克索", lng: 32.6 },
      { name: "亞斯文", lng: 32.9 },
    ]},
    { code: "NG", name: "奈及利亞", provinces: [
      { name: "拉各斯", lng: 3.4 },
      { name: "阿布賈", lng: 7.5 },
      { name: "卡諾", lng: 8.5 },
      { name: "伊巴丹（奧約州）", lng: 3.9 },
      { name: "阿比亞（阿巴）", lng: 7.4 },
    ]},
    { code: "KE", name: "肯亞", provinces: [
      { name: "奈洛比", lng: 36.8 },
      { name: "蒙巴薩", lng: 39.7 },
      { name: "基蘇木", lng: 34.8 },
    ]},
    { code: "MA", name: "摩洛哥", provinces: [
      { name: "卡薩布蘭加", lng: -7.6 },
      { name: "拉巴特", lng: -6.8 },
      { name: "馬拉喀什", lng: -8.0 },
      { name: "菲斯", lng: -5.0 },
    ]},
    { code: "GH", name: "加納", provinces: [
      { name: "阿克拉", lng: -0.2 },
      { name: "庫馬西", lng: -1.6 },
    ]},
    { code: "ET", name: "衣索比亞", provinces: [
      { name: "阿迪斯阿貝巴", lng: 38.7 },
      { name: "德雷達瓦", lng: 41.9 },
    ]},
    { code: "IL", name: "以色列", provinces: [
      { name: "特拉維夫", lng: 34.8 },
      { name: "耶路撒冷", lng: 35.2 },
      { name: "海法", lng: 35.0 },
    ]},
    { code: "TR", name: "土耳其", provinces: [
      { name: "伊斯坦堡", lng: 29.0 },
      { name: "安卡拉", lng: 32.9 },
      { name: "伊茲密爾", lng: 27.1 },
      { name: "布爾薩", lng: 29.1 },
      { name: "安塔利亞", lng: 30.7 },
      { name: "加濟安泰普", lng: 37.4 },
    ]},
    { code: "IR", name: "伊朗", provinces: [
      { name: "德黑蘭", lng: 51.4 },
      { name: "伊斯法罕", lng: 51.7 },
      { name: "設拉子", lng: 52.5 },
      { name: "大不里士", lng: 46.3 },
      { name: "馬什哈德", lng: 59.6 },
    ]},
    { code: "IQ", name: "伊拉克", provinces: [
      { name: "巴格達", lng: 44.4 },
      { name: "巴士拉", lng: 47.8 },
      { name: "摩蘇爾", lng: 43.1 },
      { name: "艾比爾（庫爾德斯坦）", lng: 44.0 },
    ]},
    { code: "PK", name: "巴基斯坦", provinces: [
      { name: "卡拉奇（信德省）", lng: 67.0 },
      { name: "拉合爾（旁遮普省）", lng: 74.3 },
      { name: "伊斯蘭馬巴德", lng: 73.1 },
      { name: "白沙瓦（開伯爾-普赫圖赫瓦省）", lng: 71.6 },
      { name: "奎達（俾路支省）", lng: 67.0 },
    ]},
    { code: "BD", name: "孟加拉", provinces: [
      { name: "達卡", lng: 90.4 },
      { name: "吉大港", lng: 91.8 },
      { name: "庫爾納", lng: 89.6 },
    ]},
    { code: "LK", name: "斯里蘭卡", provinces: [
      { name: "可倫坡", lng: 79.8 },
      { name: "康提", lng: 80.6 },
      { name: "賈夫納", lng: 80.0 },
    ]},
    { code: "MM", name: "緬甸", provinces: [
      { name: "仰光", lng: 96.2 },
      { name: "內比都", lng: 96.1 },
      { name: "曼德勒", lng: 96.1 },
    ]},
    { code: "KH", name: "柬埔寨", provinces: [
      { name: "金邊", lng: 104.9 },
      { name: "暹粒", lng: 103.9 },
    ]},
    { code: "LA", name: "寮國", provinces: [
      { name: "永珍", lng: 102.6 },
      { name: "龍坡邦", lng: 102.1 },
    ]},
    { code: "BN", name: "汶萊", provinces: [{ name: "斯里巴加灣", lng: 114.9 }] },
    { code: "MN", name: "蒙古", provinces: [
      { name: "烏蘭巴托", lng: 106.9 },
      { name: "達爾汗", lng: 105.9 },
    ]},
    { code: "KZ", name: "哈薩克", provinces: [
      { name: "阿拉木圖", lng: 76.9 },
      { name: "努爾蘇丹（阿斯塔納）", lng: 71.4 },
      { name: "希姆肯特", lng: 69.6 },
    ]},
    { code: "UZ", name: "烏茲別克", provinces: [
      { name: "塔什干", lng: 69.3 },
      { name: "撒馬爾罕", lng: 66.9 },
      { name: "布哈拉", lng: 64.4 },
    ]},
    { code: "NL", name: "荷蘭", provinces: [
      { name: "阿姆斯特丹", lng: 4.9 },
      { name: "鹿特丹", lng: 4.5 },
      { name: "海牙", lng: 4.3 },
    ]},
    { code: "BE", name: "比利時", provinces: [
      { name: "布魯塞爾", lng: 4.4 },
      { name: "安特衛普", lng: 4.4 },
      { name: "根特", lng: 3.7 },
    ]},
    { code: "CH", name: "瑞士", provinces: [
      { name: "蘇黎世", lng: 8.5 },
      { name: "日內瓦", lng: 6.1 },
      { name: "伯恩", lng: 7.4 },
      { name: "巴塞爾", lng: 7.6 },
    ]},
    { code: "AT", name: "奧地利", provinces: [
      { name: "維也納", lng: 16.4 },
      { name: "格拉茲（施泰爾馬克）", lng: 15.4 },
      { name: "林茨（上奧地利）", lng: 14.3 },
      { name: "薩爾斯堡", lng: 13.0 },
      { name: "因斯布魯克（蒂羅爾）", lng: 11.4 },
    ]},
    { code: "SE", name: "瑞典", provinces: [
      { name: "斯德哥爾摩", lng: 18.1 },
      { name: "哥德堡", lng: 11.9 },
      { name: "馬爾默", lng: 13.0 },
      { name: "于默奧", lng: 20.3 },
    ]},
    { code: "NO", name: "挪威", provinces: [
      { name: "奧斯陸", lng: 10.7 },
      { name: "卑爾根", lng: 5.3 },
      { name: "特隆赫姆", lng: 10.4 },
      { name: "特羅姆瑟", lng: 18.9 },
    ]},
    { code: "DK", name: "丹麥", provinces: [
      { name: "哥本哈根", lng: 12.6 },
      { name: "奧胡斯", lng: 10.2 },
      { name: "奧登塞", lng: 10.4 },
    ]},
    { code: "FI", name: "芬蘭", provinces: [
      { name: "赫爾辛基", lng: 25.0 },
      { name: "坦佩雷", lng: 23.8 },
      { name: "圖爾庫", lng: 22.3 },
      { name: "奧盧", lng: 25.5 },
    ]},
    { code: "PL", name: "波蘭", provinces: [
      { name: "華沙", lng: 21.0 },
      { name: "克拉科夫", lng: 20.0 },
      { name: "弗羅茨瓦夫", lng: 17.0 },
      { name: "格但斯克", lng: 18.6 },
      { name: "波茲南", lng: 16.9 },
    ]},
    { code: "CZ", name: "捷克", provinces: [
      { name: "布拉格", lng: 14.5 },
      { name: "布爾諾", lng: 16.6 },
      { name: "奧斯特拉法", lng: 18.3 },
    ]},
    { code: "PT", name: "葡萄牙", provinces: [
      { name: "里斯本", lng: -9.1 },
      { name: "波爾圖", lng: -8.6 },
      { name: "法魯（阿爾加維）", lng: -7.9 },
      { name: "亞速爾群島（蓬塔德爾加達）", lng: -25.7 },
      { name: "馬德拉島（豐沙爾）", lng: -16.9 },
    ]},
    { code: "GR", name: "希臘", provinces: [
      { name: "雅典", lng: 23.7 },
      { name: "塞薩洛尼基", lng: 23.0 },
      { name: "帕特雷", lng: 21.7 },
      { name: "克里特島（伊拉克利翁）", lng: 25.1 },
    ]},
    { code: "HU", name: "匈牙利", provinces: [
      { name: "布達佩斯", lng: 19.0 },
      { name: "德布勒森", lng: 21.6 },
      { name: "米什科爾茨", lng: 20.8 },
    ]},
    { code: "RO", name: "羅馬尼亞", provinces: [
      { name: "布加勒斯特", lng: 26.1 },
      { name: "克盧日-納波卡", lng: 23.6 },
      { name: "蒂米什瓦拉", lng: 21.2 },
      { name: "雅西", lng: 27.6 },
    ]},
    { code: "UA", name: "烏克蘭", provinces: [
      { name: "基輔", lng: 30.5 },
      { name: "哈爾科夫", lng: 36.2 },
      { name: "敖德薩", lng: 30.7 },
      { name: "第聶伯羅（第聶伯羅彼得羅夫斯克）", lng: 35.0 },
      { name: "利沃夫", lng: 24.0 },
    ]},
    { code: "NZ", name: "紐西蘭", provinces: [
      { name: "奧克蘭", lng: 174.8 },
      { name: "威靈頓", lng: 174.8 },
      { name: "基督城", lng: 172.6 },
      { name: "但尼丁", lng: 170.5 },
    ]},
    { code: "HR", name: "克羅埃西亞", provinces: [
      { name: "薩格勒布", lng: 16.0 },
      { name: "斯普利特", lng: 16.4 },
      { name: "里耶卡", lng: 14.4 },
    ]},
    { code: "RS", name: "塞爾維亞", provinces: [
      { name: "貝爾格勒", lng: 20.5 },
      { name: "諾維薩德", lng: 19.8 },
      { name: "尼什", lng: 21.9 },
    ]},
    { code: "SK", name: "斯洛伐克", provinces: [
      { name: "布拉提斯拉瓦", lng: 17.1 },
      { name: "科希策", lng: 21.2 },
    ]},
    { code: "BG", name: "保加利亞", provinces: [
      { name: "索菲亞", lng: 23.3 },
      { name: "普羅夫迪夫", lng: 24.7 },
      { name: "瓦爾納", lng: 27.9 },
    ]},
    { code: "LT", name: "立陶宛", provinces: [
      { name: "維爾紐斯", lng: 25.3 },
      { name: "考納斯", lng: 23.9 },
      { name: "克萊佩達", lng: 21.1 },
    ]},
    { code: "LV", name: "拉脫維亞", provinces: [
      { name: "里加", lng: 24.1 },
      { name: "達烏加夫皮爾斯", lng: 26.5 },
    ]},
    { code: "EE", name: "愛沙尼亞", provinces: [
      { name: "塔林", lng: 24.7 },
      { name: "塔爾圖", lng: 26.7 },
    ]},
    { code: "IS", name: "冰島", provinces: [
      { name: "雷克雅維克", lng: -22.0 },
      { name: "阿克雷里", lng: -18.1 },
    ]},
    { code: "IE", name: "愛爾蘭", provinces: [
      { name: "都柏林", lng: -6.3 },
      { name: "科克", lng: -8.5 },
      { name: "戈爾韋", lng: -9.1 },
    ]},
    { code: "VE", name: "委內瑞拉", provinces: [
      { name: "卡拉卡斯", lng: -66.9 },
      { name: "馬拉開波（蘇利亞州）", lng: -71.6 },
      { name: "巴倫西亞（卡拉沃沃州）", lng: -68.0 },
    ]},
    { code: "EC", name: "厄瓜多", provinces: [
      { name: "基多", lng: -78.5 },
      { name: "瓜亞基爾", lng: -79.9 },
      { name: "庫恩卡", lng: -79.0 },
    ]},
    { code: "BO", name: "玻利維亞", provinces: [
      { name: "拉巴斯", lng: -68.1 },
      { name: "聖克魯斯", lng: -63.2 },
      { name: "科恰班巴", lng: -66.2 },
    ]},
    { code: "PY", name: "巴拉圭", provinces: [
      { name: "亞松森", lng: -57.6 },
      { name: "恩卡納西翁", lng: -55.9 },
    ]},
    { code: "UY", name: "烏拉圭", provinces: [
      { name: "蒙特維多", lng: -56.2 },
      { name: "薩爾托", lng: -57.9 },
    ]},
    { code: "CR", name: "哥斯大黎加", provinces: [
      { name: "聖荷西", lng: -84.1 },
      { name: "利蒙", lng: -83.0 },
    ]},
    { code: "PA", name: "巴拿馬", provinces: [
      { name: "巴拿馬城", lng: -79.5 },
      { name: "科隆", lng: -79.9 },
    ]},
    { code: "JO", name: "約旦", provinces: [
      { name: "安曼", lng: 35.9 },
      { name: "亞喀巴", lng: 35.0 },
    ]},
    { code: "LB", name: "黎巴嫩", provinces: [
      { name: "貝魯特", lng: 35.5 },
      { name: "的黎波里", lng: 35.8 },
    ]},
    { code: "KW", name: "科威特", provinces: [{ name: "科威特市", lng: 47.9 }] },
    { code: "QA", name: "卡達", provinces: [{ name: "杜哈", lng: 51.5 }] },
    { code: "BH", name: "巴林", provinces: [{ name: "麥納馬", lng: 50.6 }] },
    { code: "OM", name: "阿曼", provinces: [
      { name: "馬斯喀特", lng: 58.6 },
      { name: "薩拉拉", lng: 54.1 },
    ]},
    { code: "YE", name: "葉門", provinces: [
      { name: "薩那", lng: 44.2 },
      { name: "亞丁", lng: 45.0 },
    ]},
    { code: "AF", name: "阿富汗", provinces: [
      { name: "喀布爾", lng: 69.2 },
      { name: "坎大哈", lng: 65.7 },
      { name: "赫拉特", lng: 62.2 },
    ]},
    { code: "NP", name: "尼泊爾", provinces: [
      { name: "加德滿都", lng: 85.3 },
      { name: "博卡拉", lng: 84.0 },
    ]},
    { code: "TZ", name: "坦尚尼亞", provinces: [
      { name: "三蘭港", lng: 39.3 },
      { name: "三蘭港（桑吉巴）", lng: 39.2 },
      { name: "阿魯沙", lng: 36.7 },
    ]},
    { code: "UG", name: "烏干達", provinces: [
      { name: "坎帕拉", lng: 32.6 },
      { name: "金加利（姆巴萊）", lng: 34.2 },
    ]},
    { code: "RW", name: "盧安達", provinces: [{ name: "吉佳利", lng: 30.1 }] },
    { code: "CM", name: "喀麥隆", provinces: [
      { name: "雅溫德", lng: 11.5 },
      { name: "杜阿拉", lng: 9.7 },
    ]},
    { code: "CI", name: "象牙海岸", provinces: [
      { name: "阿必尚", lng: -4.0 },
      { name: "亞穆蘇克羅（首都）", lng: -5.3 },
    ]},
    { code: "SN", name: "塞內加爾", provinces: [
      { name: "達卡", lng: -17.4 },
      { name: "基達（圖巴）", lng: -15.6 },
    ]},
    { code: "TN", name: "突尼西亞", provinces: [
      { name: "突尼斯", lng: 10.2 },
      { name: "斯法克斯", lng: 10.8 },
    ]},
    { code: "DZ", name: "阿爾及利亞", provinces: [
      { name: "阿爾及爾", lng: 3.1 },
      { name: "奧蘭", lng: -0.6 },
      { name: "君士坦丁", lng: 6.6 },
    ]},
    { code: "LY", name: "利比亞", provinces: [
      { name: "的黎波里", lng: 13.2 },
      { name: "班加西", lng: 20.1 },
    ]},
    { code: "SD", name: "蘇丹", provinces: [
      { name: "喀土穆", lng: 32.5 },
      { name: "恩圖曼", lng: 32.5 },
      { name: "港蘇丹", lng: 37.2 },
    ]},
    { code: "MZ", name: "莫三比克", provinces: [
      { name: "馬布托", lng: 32.6 },
      { name: "貝拉", lng: 34.8 },
    ]},
    { code: "ZM", name: "尚比亞", provinces: [
      { name: "盧薩卡", lng: 28.3 },
      { name: "恩多拉（銅帶省）", lng: 28.6 },
    ]},
    { code: "ZW", name: "辛巴威", provinces: [
      { name: "哈拉雷", lng: 31.0 },
      { name: "布拉瓦約", lng: 28.6 },
    ]},
    { code: "AO", name: "安哥拉", provinces: [
      { name: "羅安達", lng: 13.2 },
      { name: "胡安博", lng: 15.7 },
      { name: "本格拉", lng: 13.4 },
    ]},
    { code: "PS", name: "巴勒斯坦", provinces: [
      { name: "西岸", lng: 35.1 },
      { name: "加薩", lng: 34.5 },
    ]},
    { code: "XK", name: "科索沃", provinces: [
      { name: "普里什蒂納", lng: 21.2 },
    ]},
    { code: "GE", name: "喬治亞", provinces: [
      { name: "提比里西", lng: 44.8 },
      { name: "巴統", lng: 41.6 },
    ]},
    { code: "AM", name: "亞美尼亞", provinces: [
      { name: "葉里溫", lng: 44.5 },
    ]},
    { code: "AZ", name: "亞塞拜然", provinces: [
      { name: "巴庫", lng: 49.9 },
      { name: "根賈", lng: 46.4 },
    ]},
    { code: "BY", name: "白俄羅斯", provinces: [
      { name: "明斯克", lng: 27.6 },
      { name: "布列斯特", lng: 23.7 },
    ]},
    { code: "MD", name: "摩爾多瓦", provinces: [
      { name: "基希納烏", lng: 28.9 },
    ]},
    { code: "SI", name: "斯洛維尼亞", provinces: [
      { name: "盧布爾雅那", lng: 14.5 },
    ]},
    { code: "BA", name: "波士尼亞與赫塞哥維納", provinces: [
      { name: "塞拉耶佛", lng: 18.4 },
      { name: "巴尼亞盧卡", lng: 17.2 },
    ]},
    { code: "ME", name: "蒙特內哥羅", provinces: [
      { name: "波德戈里察", lng: 19.3 },
    ]},
    { code: "MK", name: "北馬其頓", provinces: [
      { name: "史高比耶", lng: 21.4 },
    ]},
    { code: "AL", name: "阿爾巴尼亞", provinces: [
      { name: "地拉那", lng: 19.8 },
      { name: "都拉斯", lng: 19.5 },
    ]},
    { code: "LU", name: "盧森堡", provinces: [
      { name: "盧森堡市", lng: 6.1 },
    ]},
    { code: "MT", name: "馬爾他", provinces: [
      { name: "瓦萊塔", lng: 14.5 },
    ]},
    { code: "CY", name: "賽普勒斯", provinces: [
      { name: "尼科西亞", lng: 33.4 },
      { name: "利馬索", lng: 33.0 },
    ]},
    { code: "LI", name: "列支敦斯登", provinces: [
      { name: "瓦杜茲", lng: 9.5 },
    ]},
    { code: "AD", name: "安道爾", provinces: [
      { name: "安道爾城", lng: 1.5 },
    ]},
    { code: "MC", name: "摩納哥", provinces: [
      { name: "摩納哥", lng: 7.4 },
    ]},
    { code: "SM", name: "聖馬利諾", provinces: [
      { name: "聖馬利諾", lng: 12.5 },
    ]},
    { code: "VA", name: "梵蒂岡", provinces: [
      { name: "梵蒂岡城", lng: 12.5 },
    ]},
    { code: "SY", name: "敘利亞", provinces: [
      { name: "大馬士革", lng: 36.3 },
      { name: "阿勒坡", lng: 37.2 },
      { name: "霍姆斯", lng: 36.7 },
    ]},
    { code: "KP", name: "北韓", provinces: [
      { name: "平壤", lng: 125.7 },
      { name: "清津", lng: 129.7 },
    ]},
    { code: "KG", name: "吉爾吉斯", provinces: [
      { name: "比斯凱克", lng: 74.6 },
      { name: "奧什", lng: 72.8 },
    ]},
    { code: "TJ", name: "塔吉克", provinces: [
      { name: "杜尚別", lng: 68.8 },
    ]},
    { code: "TM", name: "土庫曼", provinces: [
      { name: "阿什哈巴德", lng: 58.4 },
    ]},
    { code: "TL", name: "東帝汶", provinces: [
      { name: "帝力", lng: 125.6 },
    ]},
    { code: "BT", name: "不丹", provinces: [
      { name: "廷布", lng: 89.6 },
    ]},
    { code: "MV", name: "馬爾地夫", provinces: [
      { name: "馬累", lng: 73.5 },
    ]},
    { code: "GT", name: "瓜地馬拉", provinces: [
      { name: "瓜地馬拉市", lng: -90.5 },
      { name: "克薩爾特南戈", lng: -91.5 },
    ]},
    { code: "HN", name: "宏都拉斯", provinces: [
      { name: "德古西加巴", lng: -87.2 },
      { name: "聖佩德羅蘇拉", lng: -88.0 },
    ]},
    { code: "SV", name: "薩爾瓦多", provinces: [
      { name: "聖薩爾瓦多", lng: -89.2 },
    ]},
    { code: "NI", name: "尼加拉瓜", provinces: [
      { name: "馬拿瓜", lng: -86.3 },
    ]},
    { code: "CU", name: "古巴", provinces: [
      { name: "哈瓦那", lng: -82.4 },
      { name: "聖地牙哥德古巴", lng: -75.8 },
    ]},
    { code: "JM", name: "牙買加", provinces: [
      { name: "京斯敦", lng: -76.8 },
    ]},
    { code: "HT", name: "海地", provinces: [
      { name: "太子港", lng: -72.3 },
    ]},
    { code: "DO", name: "多明尼加", provinces: [
      { name: "聖多明哥", lng: -69.9 },
    ]},
    { code: "TT", name: "千里達與托巴哥", provinces: [
      { name: "西班牙港", lng: -61.5 },
    ]},
    { code: "BB", name: "巴貝多", provinces: [
      { name: "布里奇敦", lng: -59.6 },
    ]},
    { code: "BS", name: "巴哈馬", provinces: [
      { name: "拿騷", lng: -77.4 },
    ]},
    { code: "BZ", name: "貝里斯", provinces: [
      { name: "貝爾莫潘", lng: -88.8 },
    ]},
    { code: "GY", name: "蓋亞那", provinces: [
      { name: "喬治敦", lng: -58.2 },
    ]},
    { code: "SR", name: "蘇利南", provinces: [
      { name: "巴拉馬里博", lng: -55.2 },
    ]},
    { code: "CD", name: "剛果民主共和國", provinces: [
      { name: "金夏沙", lng: 15.3 },
      { name: "盧本巴希", lng: 27.5 },
    ]},
    { code: "CG", name: "剛果共和國", provinces: [
      { name: "布拉薩維爾", lng: 15.3 },
    ]},
    { code: "ML", name: "馬利", provinces: [
      { name: "巴馬科", lng: -8.0 },
    ]},
    { code: "BF", name: "布吉納法索", provinces: [
      { name: "瓦加杜古", lng: -1.5 },
    ]},
    { code: "NE", name: "尼日", provinces: [
      { name: "尼阿美", lng: 2.1 },
    ]},
    { code: "TD", name: "查德", provinces: [
      { name: "恩賈梅納", lng: 15.1 },
    ]},
    { code: "MR", name: "茅利塔尼亞", provinces: [
      { name: "努瓦克肖特", lng: -15.9 },
    ]},
    { code: "SL", name: "獅子山", provinces: [
      { name: "自由城", lng: -13.2 },
    ]},
    { code: "LR", name: "賴比瑞亞", provinces: [
      { name: "蒙羅維亞", lng: -10.8 },
    ]},
    { code: "GN", name: "幾內亞", provinces: [
      { name: "柯那克里", lng: -13.7 },
    ]},
    { code: "GW", name: "幾內亞比索", provinces: [
      { name: "比索", lng: -15.6 },
    ]},
    { code: "GM", name: "甘比亞", provinces: [
      { name: "班珠爾", lng: -16.6 },
    ]},
    { code: "TG", name: "多哥", provinces: [
      { name: "洛美", lng: 1.2 },
    ]},
    { code: "BJ", name: "貝南", provinces: [
      { name: "科托努", lng: 2.4 },
    ]},
    { code: "GA", name: "加蓬", provinces: [
      { name: "自由市", lng: 9.5 },
    ]},
    { code: "GQ", name: "赤道幾內亞", provinces: [
      { name: "馬拉博", lng: 8.8 },
    ]},
    { code: "ST", name: "聖多美普林西比", provinces: [
      { name: "聖多美", lng: 6.7 },
    ]},
    { code: "CF", name: "中非共和國", provinces: [
      { name: "班基", lng: 18.6 },
    ]},
    { code: "SS", name: "南蘇丹", provinces: [
      { name: "朱巴", lng: 31.6 },
    ]},
    { code: "BI", name: "蒲隆地", provinces: [
      { name: "吉特加", lng: 29.9 },
      { name: "布松布拉", lng: 29.4 },
    ]},
    { code: "DJ", name: "吉布地", provinces: [
      { name: "吉布地市", lng: 43.1 },
    ]},
    { code: "SO", name: "索馬利亞", provinces: [
      { name: "摩加迪休", lng: 45.3 },
      { name: "哈爾格薩", lng: 44.1 },
    ]},
    { code: "ER", name: "厄利垂亞", provinces: [
      { name: "阿斯馬拉", lng: 38.9 },
    ]},
    { code: "MG", name: "馬達加斯加", provinces: [
      { name: "塔那那利佛", lng: 47.5 },
      { name: "多法納", lng: 49.4 },
    ]},
    { code: "MW", name: "馬拉威", provinces: [
      { name: "里朗威", lng: 33.8 },
      { name: "布蘭太爾", lng: 35.0 },
    ]},
    { code: "BW", name: "波扎那", provinces: [
      { name: "嘉柏隆里", lng: 25.9 },
    ]},
    { code: "NA", name: "納米比亞", provinces: [
      { name: "溫得和克", lng: 17.1 },
    ]},
    { code: "LS", name: "賴索托", provinces: [
      { name: "馬塞盧", lng: 27.5 },
    ]},
    { code: "SZ", name: "史瓦帝尼", provinces: [
      { name: "姆巴本", lng: 31.5 },
    ]},
    { code: "MU", name: "模里西斯", provinces: [
      { name: "路易斯港", lng: 57.5 },
    ]},
    { code: "SC", name: "塞席爾", provinces: [
      { name: "維多利亞", lng: 55.5 },
    ]},
    { code: "KM", name: "葛摩", provinces: [
      { name: "莫洛尼", lng: 43.3 },
    ]},
    { code: "FJ", name: "斐濟", provinces: [
      { name: "蘇瓦", lng: 178.4 },
    ]},
    { code: "PG", name: "巴布亞紐幾內亞", provinces: [
      { name: "莫爾茲比港", lng: 147.2 },
    ]},
    { code: "SB", name: "索羅門群島", provinces: [
      { name: "荷尼阿拉", lng: 159.9 },
    ]},
    { code: "VU", name: "萬那杜", provinces: [
      { name: "維拉港", lng: 168.3 },
    ]},
    { code: "WS", name: "薩摩亞", provinces: [
      { name: "阿皮亞", lng: -171.8 },
    ]},
    { code: "TO", name: "東加", provinces: [
      { name: "努瓜婁發", lng: -175.2 },
    ]},
    { code: "KI", name: "吉里巴斯", provinces: [
      { name: "塔拉瓦", lng: 173.0 },
    ]},
    { code: "FM", name: "密克羅尼西亞", provinces: [
      { name: "帕利基爾", lng: 158.2 },
    ]},
    { code: "MH", name: "馬紹爾群島", provinces: [
      { name: "馬久羅", lng: 171.4 },
    ]},
    { code: "PW", name: "帛琉", provinces: [
      { name: "恩格魯穆德", lng: 134.5 },
    ]},
    { code: "NR", name: "諾魯", provinces: [
      { name: "亞倫", lng: 166.9 },
    ]},
    { code: "TV", name: "吐瓦魯", provinces: [
      { name: "富那富提", lng: 179.2 },
    ]},
    { code: "CV", name: "維德角", provinces: [
      { name: "普拉亞", lng: -23.5 },
    ]},
    { code: "OTHER", name: "其他", provinces: [{ name: "其他地區", lng: 120.0 }] },
  ],

  occupations: [
    "學生", "教育／研究", "醫療／護理／藥學",
    "資訊／軟體／工程", "金融／銀行／保險／投資",
    "法律／會計／顧問", "藝術／設計／文創",
    "媒體／傳播／出版", "服務業（餐飲／旅館／零售）",
    "製造／加工／生產", "建築／不動產／室內設計",
    "農林漁牧", "運輸／物流", "公部門／軍警消",
    "宗教／靈性／命理", "自由業／創業", "家管", "退休", "待業／轉職中", "其他",
  ],

  hours: Array.from({length: 24}, (_, i) => i),
  minutes: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
};
