// 引路人 Lumora · 前端常數資料

// 國家 + 省/地區（含經度概估，用於真太陽時校正）
window.LUMORA_DATA = {
  countries: [
    { code: "TW", name: "台灣", provinces: [
      { name: "台北", lng: 121.5 },
      { name: "新北", lng: 121.4 },
      { name: "桃園", lng: 121.3 },
      { name: "新竹", lng: 121.0 },
      { name: "苗栗", lng: 120.8 },
      { name: "台中", lng: 120.7 },
      { name: "彰化", lng: 120.5 },
      { name: "南投", lng: 120.7 },
      { name: "雲林", lng: 120.5 },
      { name: "嘉義", lng: 120.4 },
      { name: "台南", lng: 120.2 },
      { name: "高雄", lng: 120.3 },
      { name: "屏東", lng: 120.5 },
      { name: "宜蘭", lng: 121.7 },
      { name: "花蓮", lng: 121.6 },
      { name: "台東", lng: 121.1 },
      { name: "澎湖", lng: 119.6 },
      { name: "金門", lng: 118.3 },
      { name: "馬祖", lng: 119.9 },
      { name: "基隆", lng: 121.7 },
    ]},
    { code: "CN", name: "中國大陸", provinces: [
      { name: "北京", lng: 116.4 },
      { name: "上海", lng: 121.5 },
      { name: "天津", lng: 117.2 },
      { name: "重慶", lng: 106.5 },
      { name: "河北（石家莊）", lng: 114.5 },
      { name: "山西（太原）", lng: 112.5 },
      { name: "遼寧（瀋陽）", lng: 123.4 },
      { name: "吉林（長春）", lng: 125.3 },
      { name: "黑龍江（哈爾濱）", lng: 126.6 },
      { name: "江蘇（南京）", lng: 118.8 },
      { name: "浙江（杭州）", lng: 120.2 },
      { name: "安徽（合肥）", lng: 117.3 },
      { name: "福建（福州）", lng: 119.3 },
      { name: "江西（南昌）", lng: 115.9 },
      { name: "山東（濟南）", lng: 117.0 },
      { name: "河南（鄭州）", lng: 113.6 },
      { name: "湖北（武漢）", lng: 114.3 },
      { name: "湖南（長沙）", lng: 112.9 },
      { name: "廣東（廣州）", lng: 113.3 },
      { name: "廣西（南寧）", lng: 108.4 },
      { name: "海南（海口）", lng: 110.3 },
      { name: "四川（成都）", lng: 104.1 },
      { name: "貴州（貴陽）", lng: 106.7 },
      { name: "雲南（昆明）", lng: 102.7 },
      { name: "西藏（拉薩）", lng: 91.1 },
      { name: "陝西（西安）", lng: 108.9 },
      { name: "甘肅（蘭州）", lng: 103.8 },
      { name: "青海（西寧）", lng: 101.8 },
      { name: "寧夏（銀川）", lng: 106.3 },
      { name: "新疆（烏魯木齊）", lng: 87.6 },
      { name: "內蒙古（呼和浩特）", lng: 111.7 },
      { name: "香港", lng: 114.2 },
      { name: "澳門", lng: 113.5 },
    ]},
    { code: "JP", name: "日本", provinces: [
      { name: "東京", lng: 139.7 },
      { name: "大阪", lng: 135.5 },
      { name: "京都", lng: 135.8 },
      { name: "名古屋", lng: 136.9 },
      { name: "北海道（札幌）", lng: 141.4 },
      { name: "福岡", lng: 130.4 },
      { name: "沖繩（那霸）", lng: 127.7 },
      { name: "仙台", lng: 140.9 },
      { name: "廣島", lng: 132.5 },
    ]},
    { code: "KR", name: "韓國", provinces: [
      { name: "首爾", lng: 127.0 },
      { name: "釜山", lng: 129.0 },
      { name: "大邱", lng: 128.6 },
      { name: "仁川", lng: 126.7 },
    ]},
    { code: "US", name: "美國", provinces: [
      { name: "紐約", lng: -74.0 },
      { name: "洛杉磯", lng: -118.2 },
      { name: "舊金山", lng: -122.4 },
      { name: "芝加哥", lng: -87.6 },
      { name: "西雅圖", lng: -122.3 },
      { name: "華盛頓特區", lng: -77.0 },
      { name: "波士頓", lng: -71.1 },
      { name: "邁阿密", lng: -80.2 },
      { name: "達拉斯", lng: -96.8 },
      { name: "休斯頓", lng: -95.4 },
      { name: "亞特蘭大", lng: -84.4 },
      { name: "夏威夷（檀香山）", lng: -157.8 },
    ]},
    { code: "GB", name: "英國", provinces: [
      { name: "倫敦", lng: -0.1 },
      { name: "曼徹斯特", lng: -2.2 },
      { name: "愛丁堡", lng: -3.2 },
    ]},
    { code: "SG", name: "新加坡", provinces: [{ name: "新加坡", lng: 103.8 }] },
    { code: "MY", name: "馬來西亞", provinces: [
      { name: "吉隆坡", lng: 101.7 },
      { name: "檳城", lng: 100.3 },
      { name: "新山", lng: 103.8 },
    ]},
    { code: "TH", name: "泰國", provinces: [
      { name: "曼谷", lng: 100.5 },
      { name: "清邁", lng: 99.0 },
    ]},
    { code: "VN", name: "越南", provinces: [
      { name: "胡志明市", lng: 106.7 },
      { name: "河內", lng: 105.8 },
    ]},
    { code: "ID", name: "印尼", provinces: [
      { name: "雅加達", lng: 106.8 },
      { name: "峇里", lng: 115.2 },
    ]},
    { code: "PH", name: "菲律賓", provinces: [{ name: "馬尼拉", lng: 121.0 }] },
    { code: "AU", name: "澳大利亞", provinces: [
      { name: "雪梨", lng: 151.2 },
      { name: "墨爾本", lng: 145.0 },
      { name: "布里斯本", lng: 153.0 },
    ]},
    { code: "CA", name: "加拿大", provinces: [
      { name: "多倫多", lng: -79.4 },
      { name: "溫哥華", lng: -123.1 },
      { name: "蒙特婁", lng: -73.6 },
    ]},
    { code: "DE", name: "德國", provinces: [
      { name: "柏林", lng: 13.4 },
      { name: "慕尼黑", lng: 11.6 },
    ]},
    { code: "FR", name: "法國", provinces: [{ name: "巴黎", lng: 2.4 }] },
    { code: "IT", name: "義大利", provinces: [{ name: "羅馬", lng: 12.5 }] },
    { code: "ES", name: "西班牙", provinces: [{ name: "馬德里", lng: -3.7 }] },
    { code: "IN", name: "印度", provinces: [
      { name: "新德里", lng: 77.2 },
      { name: "孟買", lng: 72.9 },
      { name: "班加羅爾", lng: 77.6 },
      { name: "清奈", lng: 80.3 },
    ]},
    { code: "RU", name: "俄羅斯", provinces: [
      { name: "莫斯科", lng: 37.6 },
      { name: "聖彼得堡", lng: 30.3 },
      { name: "海參崴", lng: 132.0 },
    ]},
    { code: "BR", name: "巴西", provinces: [
      { name: "聖保羅", lng: -46.6 },
      { name: "里約熱內盧", lng: -43.2 },
      { name: "巴西利亞", lng: -47.9 },
    ]},
    { code: "MX", name: "墨西哥", provinces: [
      { name: "墨西哥城", lng: -99.1 },
      { name: "蒙特雷", lng: -100.3 },
    ]},
    { code: "AR", name: "阿根廷", provinces: [{ name: "布宜諾斯艾利斯", lng: -58.4 }] },
    { code: "CL", name: "智利", provinces: [{ name: "聖地亞哥", lng: -70.7 }] },
    { code: "CO", name: "哥倫比亞", provinces: [{ name: "波哥大", lng: -74.1 }] },
    { code: "PE", name: "秘魯", provinces: [{ name: "利馬", lng: -77.0 }] },
    { code: "ZA", name: "南非", provinces: [
      { name: "約翰尼斯堡", lng: 28.0 },
      { name: "開普敦", lng: 18.4 },
    ]},
    { code: "EG", name: "埃及", provinces: [{ name: "開羅", lng: 31.2 }] },
    { code: "NG", name: "奈及利亞", provinces: [{ name: "拉各斯", lng: 3.4 }] },
    { code: "KE", name: "肯亞", provinces: [{ name: "奈洛比", lng: 36.8 }] },
    { code: "MA", name: "摩洛哥", provinces: [{ name: "卡薩布蘭加", lng: -7.6 }] },
    { code: "GH", name: "加納", provinces: [{ name: "阿克拉", lng: -0.2 }] },
    { code: "ET", name: "衣索比亞", provinces: [{ name: "阿迪斯阿貝巴", lng: 38.7 }] },
    { code: "SA", name: "沙烏地阿拉伯", provinces: [
      { name: "利雅德", lng: 46.7 },
      { name: "吉達", lng: 39.2 },
      { name: "麥加", lng: 39.8 },
    ]},
    { code: "AE", name: "阿聯酋", provinces: [
      { name: "杜拜", lng: 55.3 },
      { name: "阿布達比", lng: 54.4 },
    ]},
    { code: "IL", name: "以色列", provinces: [{ name: "特拉維夫", lng: 34.8 }] },
    { code: "TR", name: "土耳其", provinces: [
      { name: "伊斯坦堡", lng: 29.0 },
      { name: "安卡拉", lng: 32.9 },
    ]},
    { code: "IR", name: "伊朗", provinces: [{ name: "德黑蘭", lng: 51.4 }] },
    { code: "IQ", name: "伊拉克", provinces: [{ name: "巴格達", lng: 44.4 }] },
    { code: "PK", name: "巴基斯坦", provinces: [
      { name: "卡拉奇", lng: 67.0 },
      { name: "拉合爾", lng: 74.3 },
    ]},
    { code: "BD", name: "孟加拉", provinces: [{ name: "達卡", lng: 90.4 }] },
    { code: "LK", name: "斯里蘭卡", provinces: [{ name: "可倫坡", lng: 79.8 }] },
    { code: "MM", name: "緬甸", provinces: [{ name: "仰光", lng: 96.2 }] },
    { code: "KH", name: "柬埔寨", provinces: [{ name: "金邊", lng: 104.9 }] },
    { code: "LA", name: "寮國", provinces: [{ name: "永珍", lng: 102.6 }] },
    { code: "BN", name: "汶萊", provinces: [{ name: "斯里巴加灣", lng: 114.9 }] },
    { code: "MN", name: "蒙古", provinces: [{ name: "烏蘭巴托", lng: 106.9 }] },
    { code: "KZ", name: "哈薩克", provinces: [{ name: "阿拉木圖", lng: 76.9 }] },
    { code: "UZ", name: "烏茲別克", provinces: [{ name: "塔什干", lng: 69.3 }] },
    { code: "NL", name: "荷蘭", provinces: [{ name: "阿姆斯特丹", lng: 4.9 }] },
    { code: "BE", name: "比利時", provinces: [{ name: "布魯塞爾", lng: 4.4 }] },
    { code: "CH", name: "瑞士", provinces: [{ name: "日內瓦", lng: 6.1 }, { name: "蘇黎世", lng: 8.5 }] },
    { code: "AT", name: "奧地利", provinces: [{ name: "維也納", lng: 16.4 }] },
    { code: "SE", name: "瑞典", provinces: [{ name: "斯德哥爾摩", lng: 18.1 }] },
    { code: "NO", name: "挪威", provinces: [{ name: "奧斯陸", lng: 10.7 }] },
    { code: "DK", name: "丹麥", provinces: [{ name: "哥本哈根", lng: 12.6 }] },
    { code: "FI", name: "芬蘭", provinces: [{ name: "赫爾辛基", lng: 25.0 }] },
    { code: "PL", name: "波蘭", provinces: [{ name: "華沙", lng: 21.0 }] },
    { code: "CZ", name: "捷克", provinces: [{ name: "布拉格", lng: 14.5 }] },
    { code: "PT", name: "葡萄牙", provinces: [{ name: "里斯本", lng: -9.1 }] },
    { code: "GR", name: "希臘", provinces: [{ name: "雅典", lng: 23.7 }] },
    { code: "HU", name: "匈牙利", provinces: [{ name: "布達佩斯", lng: 19.0 }] },
    { code: "RO", name: "羅馬尼亞", provinces: [{ name: "布加勒斯特", lng: 26.1 }] },
    { code: "UA", name: "烏克蘭", provinces: [{ name: "基輔", lng: 30.5 }] },
    { code: "NZ", name: "紐西蘭", provinces: [
      { name: "奧克蘭", lng: 174.8 },
      { name: "威靈頓", lng: 174.8 },
    ]},
    { code: "HR", name: "克羅埃西亞", provinces: [{ name: "薩格勒布", lng: 16.0 }] },
    { code: "RS", name: "塞爾維亞", provinces: [{ name: "貝爾格勒", lng: 20.5 }] },
    { code: "SK", name: "斯洛伐克", provinces: [{ name: "布拉提斯拉瓦", lng: 17.1 }] },
    { code: "BG", name: "保加利亞", provinces: [{ name: "索菲亞", lng: 23.3 }] },
    { code: "LT", name: "立陶宛", provinces: [{ name: "維爾紐斯", lng: 25.3 }] },
    { code: "LV", name: "拉脫維亞", provinces: [{ name: "里加", lng: 24.1 }] },
    { code: "EE", name: "愛沙尼亞", provinces: [{ name: "塔林", lng: 24.7 }] },
    { code: "IS", name: "冰島", provinces: [{ name: "雷克雅維克", lng: -22.0 }] },
    { code: "IE", name: "愛爾蘭", provinces: [{ name: "都柏林", lng: -6.3 }] },
    { code: "MX", name: "墨西哥", provinces: [{ name: "墨西哥城", lng: -99.1 }] },
    { code: "VE", name: "委內瑞拉", provinces: [{ name: "卡拉卡斯", lng: -66.9 }] },
    { code: "EC", name: "厄瓜多", provinces: [{ name: "基多", lng: -78.5 }] },
    { code: "BO", name: "玻利維亞", provinces: [{ name: "拉巴斯", lng: -68.1 }] },
    { code: "PY", name: "巴拉圭", provinces: [{ name: "亞松森", lng: -57.6 }] },
    { code: "UY", name: "烏拉圭", provinces: [{ name: "蒙特維多", lng: -56.2 }] },
    { code: "CR", name: "哥斯大黎加", provinces: [{ name: "聖荷西", lng: -84.1 }] },
    { code: "PA", name: "巴拿馬", provinces: [{ name: "巴拿馬城", lng: -79.5 }] },
    { code: "JO", name: "約旦", provinces: [{ name: "安曼", lng: 35.9 }] },
    { code: "LB", name: "黎巴嫩", provinces: [{ name: "貝魯特", lng: 35.5 }] },
    { code: "KW", name: "科威特", provinces: [{ name: "科威特市", lng: 47.9 }] },
    { code: "QA", name: "卡達", provinces: [{ name: "杜哈", lng: 51.5 }] },
    { code: "BH", name: "巴林", provinces: [{ name: "麥納馬", lng: 50.6 }] },
    { code: "OM", name: "阿曼", provinces: [{ name: "馬斯喀特", lng: 58.6 }] },
    { code: "YE", name: "葉門", provinces: [{ name: "薩那", lng: 44.2 }] },
    { code: "AF", name: "阿富汗", provinces: [{ name: "喀布爾", lng: 69.2 }] },
    { code: "NP", name: "尼泊爾", provinces: [{ name: "加德滿都", lng: 85.3 }] },
    { code: "TZ", name: "坦尚尼亞", provinces: [{ name: "三蘭港", lng: 39.3 }] },
    { code: "UG", name: "烏干達", provinces: [{ name: "坎帕拉", lng: 32.6 }] },
    { code: "RW", name: "盧安達", provinces: [{ name: "吉佳利", lng: 30.1 }] },
    { code: "CM", name: "喀麥隆", provinces: [{ name: "雅溫德", lng: 11.5 }] },
    { code: "CI", name: "象牙海岸", provinces: [{ name: "阿必尚", lng: -4.0 }] },
    { code: "SN", name: "塞內加爾", provinces: [{ name: "達卡", lng: -17.4 }] },
    { code: "TN", name: "突尼西亞", provinces: [{ name: "突尼斯", lng: 10.2 }] },
    { code: "DZ", name: "阿爾及利亞", provinces: [{ name: "阿爾及爾", lng: 3.1 }] },
    { code: "LY", name: "利比亞", provinces: [{ name: "的黎波里", lng: 13.2 }] },
    { code: "SD", name: "蘇丹", provinces: [{ name: "喀土穆", lng: 32.5 }] },
    { code: "MZ", name: "莫三比克", provinces: [{ name: "馬布托", lng: 32.6 }] },
    { code: "ZM", name: "尚比亞", provinces: [{ name: "盧薩卡", lng: 28.3 }] },
    { code: "ZW", name: "辛巴威", provinces: [{ name: "哈拉雷", lng: 31.0 }] },
    { code: "AO", name: "安哥拉", provinces: [{ name: "羅安達", lng: 13.2 }] },
    { code: "OTHER", name: "其他", provinces: [{ name: "其他地區", lng: 120.0 }] },
  ],

  occupations: [
    "學生", "教育／研究", "醫療／護理／藥學",
    "資訊／軟體／工程", "金融／銀行／保險／投資",
    "法律／會計／顧問", "藝術／設計／文創",
    "媒體／傳播／出版", "服務業（餐飲／旅館／零售）",
    "製造／加工／生產", "建築／不動產／室內設計",
    "農林漁牧", "運輸／物流", "公部門／軍警消",
    "宗教／靈性／命理", "自由業／創業", "家管", "退休", "待業／轉職中", "其他",
  ],

  hours: Array.from({length: 24}, (_, i) => i),
  minutes: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
};
