window.LUMORA_LOCATION_DATA = {
  countryCodes: [
    "AD","AE","AF","AG","AI","AL","AM","AO","AQ","AR","AS","AT","AU","AW","AX","AZ",
    "BA","BB","BD","BE","BF","BG","BH","BI","BJ","BL","BM","BN","BO","BQ","BR","BS",
    "BT","BV","BW","BY","BZ","CA","CC","CD","CF","CG","CH","CI","CK","CL","CM","CN",
    "CO","CR","CU","CV","CW","CX","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE",
    "EG","EH","ER","ES","ET","FI","FJ","FK","FM","FO","FR","GA","GB","GD","GE","GF",
    "GG","GH","GI","GL","GM","GN","GP","GQ","GR","GS","GT","GU","GW","GY","HK","HM",
    "HN","HR","HT","HU","ID","IE","IL","IM","IN","IO","IQ","IR","IS","IT","JE","JM",
    "JO","JP","KE","KG","KH","KI","KM","KN","KP","KR","KW","KY","KZ","LA","LB","LC",
    "LI","LK","LR","LS","LT","LU","LV","LY","MA","MC","MD","ME","MF","MG","MH","MK",
    "ML","MM","MN","MO","MP","MQ","MR","MS","MT","MU","MV","MW","MX","MY","MZ","NA",
    "NC","NE","NF","NG","NI","NL","NO","NP","NR","NU","NZ","OM","PA","PE","PF","PG",
    "PH","PK","PL","PM","PN","PR","PS","PT","PW","PY","QA","RE","RO","RS","RU","RW",
    "SA","SB","SC","SD","SE","SG","SH","SI","SJ","SK","SL","SM","SN","SO","SR","SS",
    "ST","SV","SX","SY","SZ","TC","TD","TF","TG","TH","TJ","TK","TL","TM","TN","TO",
    "TR","TT","TV","TW","TZ","UA","UG","UM","US","UY","UZ","VA","VC","VE","VG","VI",
    "VN","VU","WF","WS","YE","YT","ZA","ZM","ZW"
  ],
  subdivisions: {
    AU: [
      { value: "Australian Capital Territory", zh: "澳洲首都領地" },
      { value: "New South Wales", zh: "新南威爾士州" },
      { value: "Northern Territory", zh: "北領地" },
      { value: "Queensland", zh: "昆士蘭州" },
      { value: "South Australia", zh: "南澳州" },
      { value: "Tasmania", zh: "塔斯馬尼亞州" },
      { value: "Victoria", zh: "維多利亞州" },
      { value: "Western Australia", zh: "西澳州" }
    ],
    CA: [
      { value: "Alberta", zh: "亞伯達省" },
      { value: "British Columbia", zh: "卑詩省" },
      { value: "Manitoba", zh: "曼尼托巴省" },
      { value: "New Brunswick", zh: "新不倫瑞克省" },
      { value: "Newfoundland and Labrador", zh: "紐芬蘭與拉布拉多省" },
      { value: "Northwest Territories", zh: "西北地區" },
      { value: "Nova Scotia", zh: "新斯科細亞省" },
      { value: "Nunavut", zh: "努納福特地區" },
      { value: "Ontario", zh: "安大略省" },
      { value: "Prince Edward Island", zh: "愛德華王子島省" },
      { value: "Quebec", zh: "魁北克省" },
      { value: "Saskatchewan", zh: "薩斯喀徹溫省" },
      { value: "Yukon", zh: "育空地區" }
    ],
    CN: [
      { value: "Anhui", zh: "安徽" },
      { value: "Beijing", zh: "北京" },
      { value: "Chongqing", zh: "重慶" },
      { value: "Fujian", zh: "福建" },
      { value: "Gansu", zh: "甘肅" },
      { value: "Guangdong", zh: "廣東" },
      { value: "Guangxi", zh: "廣西" },
      { value: "Guizhou", zh: "貴州" },
      { value: "Hainan", zh: "海南" },
      { value: "Hebei", zh: "河北" },
      { value: "Heilongjiang", zh: "黑龍江" },
      { value: "Henan", zh: "河南" },
      { value: "Hong Kong", zh: "香港" },
      { value: "Hubei", zh: "湖北" },
      { value: "Hunan", zh: "湖南" },
      { value: "Inner Mongolia", zh: "內蒙古" },
      { value: "Jiangsu", zh: "江蘇" },
      { value: "Jiangxi", zh: "江西" },
      { value: "Jilin", zh: "吉林" },
      { value: "Liaoning", zh: "遼寧" },
      { value: "Macau", zh: "澳門" },
      { value: "Ningxia", zh: "寧夏" },
      { value: "Qinghai", zh: "青海" },
      { value: "Shaanxi", zh: "陝西" },
      { value: "Shandong", zh: "山東" },
      { value: "Shanghai", zh: "上海" },
      { value: "Shanxi", zh: "山西" },
      { value: "Sichuan", zh: "四川" },
      { value: "Taiwan", zh: "台灣" },
      { value: "Tianjin", zh: "天津" },
      { value: "Tibet", zh: "西藏" },
      { value: "Xinjiang", zh: "新疆" },
      { value: "Yunnan", zh: "雲南" },
      { value: "Zhejiang", zh: "浙江" }
    ],
    GB: [
      { value: "England", zh: "英格蘭" },
      { value: "Northern Ireland", zh: "北愛爾蘭" },
      { value: "Scotland", zh: "蘇格蘭" },
      { value: "Wales", zh: "威爾斯" }
    ],
    IN: [
      { value: "Andaman and Nicobar Islands", zh: "安達曼-尼科巴群島" },
      { value: "Andhra Pradesh", zh: "安得拉邦" },
      { value: "Arunachal Pradesh", zh: "阿魯納恰爾邦" },
      { value: "Assam", zh: "阿薩姆邦" },
      { value: "Bihar", zh: "比哈爾邦" },
      { value: "Chandigarh", zh: "昌迪加爾" },
      { value: "Chhattisgarh", zh: "恰蒂斯加爾邦" },
      { value: "Dadra and Nagar Haveli and Daman and Diu", zh: "達德拉-納加爾哈維利和達曼-第烏" },
      { value: "Delhi", zh: "德里" },
      { value: "Goa", zh: "果阿邦" },
      { value: "Gujarat", zh: "古吉拉特邦" },
      { value: "Haryana", zh: "哈里亞納邦" },
      { value: "Himachal Pradesh", zh: "喜馬偕爾邦" },
      { value: "Jammu and Kashmir", zh: "查謨和克什米爾" },
      { value: "Jharkhand", zh: "賈坎德邦" },
      { value: "Karnataka", zh: "卡納塔克邦" },
      { value: "Kerala", zh: "喀拉拉邦" },
      { value: "Ladakh", zh: "拉達克" },
      { value: "Lakshadweep", zh: "拉克沙群島" },
      { value: "Madhya Pradesh", zh: "中央邦" },
      { value: "Maharashtra", zh: "馬哈拉施特拉邦" },
      { value: "Manipur", zh: "曼尼普爾邦" },
      { value: "Meghalaya", zh: "梅加拉亞邦" },
      { value: "Mizoram", zh: "米佐拉姆邦" },
      { value: "Nagaland", zh: "那加蘭邦" },
      { value: "Odisha", zh: "奧迪沙邦" },
      { value: "Puducherry", zh: "本地治里" },
      { value: "Punjab", zh: "旁遮普邦" },
      { value: "Rajasthan", zh: "拉賈斯坦邦" },
      { value: "Sikkim", zh: "錫金邦" },
      { value: "Tamil Nadu", zh: "泰米爾納德邦" },
      { value: "Telangana", zh: "特倫甘納邦" },
      { value: "Tripura", zh: "特里普拉邦" },
      { value: "Uttar Pradesh", zh: "北方邦" },
      { value: "Uttarakhand", zh: "北阿坎德邦" },
      { value: "West Bengal", zh: "西孟加拉邦" }
    ],
    JP: [
      { value: "Aichi", zh: "愛知縣" },
      { value: "Akita", zh: "秋田縣" },
      { value: "Aomori", zh: "青森縣" },
      { value: "Chiba", zh: "千葉縣" },
      { value: "Ehime", zh: "愛媛縣" },
      { value: "Fukui", zh: "福井縣" },
      { value: "Fukuoka", zh: "福岡縣" },
      { value: "Fukushima", zh: "福島縣" },
      { value: "Gifu", zh: "岐阜縣" },
      { value: "Gunma", zh: "群馬縣" },
      { value: "Hiroshima", zh: "廣島縣" },
      { value: "Hokkaido", zh: "北海道" },
      { value: "Hyogo", zh: "兵庫縣" },
      { value: "Ibaraki", zh: "茨城縣" },
      { value: "Ishikawa", zh: "石川縣" },
      { value: "Iwate", zh: "岩手縣" },
      { value: "Kagawa", zh: "香川縣" },
      { value: "Kagoshima", zh: "鹿兒島縣" },
      { value: "Kanagawa", zh: "神奈川縣" },
      { value: "Kochi", zh: "高知縣" },
      { value: "Kumamoto", zh: "熊本縣" },
      { value: "Kyoto", zh: "京都府" },
      { value: "Mie", zh: "三重縣" },
      { value: "Miyagi", zh: "宮城縣" },
      { value: "Miyazaki", zh: "宮崎縣" },
      { value: "Nagano", zh: "長野縣" },
      { value: "Nagasaki", zh: "長崎縣" },
      { value: "Nara", zh: "奈良縣" },
      { value: "Niigata", zh: "新潟縣" },
      { value: "Oita", zh: "大分縣" },
      { value: "Okayama", zh: "岡山縣" },
      { value: "Okinawa", zh: "沖繩縣" },
      { value: "Osaka", zh: "大阪府" },
      { value: "Saga", zh: "佐賀縣" },
      { value: "Saitama", zh: "埼玉縣" },
      { value: "Shiga", zh: "滋賀縣" },
      { value: "Shimane", zh: "島根縣" },
      { value: "Shizuoka", zh: "靜岡縣" },
      { value: "Tochigi", zh: "栃木縣" },
      { value: "Tokushima", zh: "德島縣" },
      { value: "Tokyo", zh: "東京都" },
      { value: "Tottori", zh: "鳥取縣" },
      { value: "Toyama", zh: "富山縣" },
      { value: "Wakayama", zh: "和歌山縣" },
      { value: "Yamagata", zh: "山形縣" },
      { value: "Yamaguchi", zh: "山口縣" },
      { value: "Yamanashi", zh: "山梨縣" }
    ],
    KR: [
      { value: "Busan", zh: "釜山" },
      { value: "Chungcheongbuk-do", zh: "忠清北道" },
      { value: "Chungcheongnam-do", zh: "忠清南道" },
      { value: "Daegu", zh: "大邱" },
      { value: "Daejeon", zh: "大田" },
      { value: "Gangwon-do", zh: "江原道" },
      { value: "Gwangju", zh: "光州" },
      { value: "Gyeonggi-do", zh: "京畿道" },
      { value: "Gyeongsangbuk-do", zh: "慶尚北道" },
      { value: "Gyeongsangnam-do", zh: "慶尚南道" },
      { value: "Incheon", zh: "仁川" },
      { value: "Jeju-do", zh: "濟州特別自治道" },
      { value: "Jeollabuk-do", zh: "全羅北道" },
      { value: "Jeollanam-do", zh: "全羅南道" },
      { value: "Sejong", zh: "世宗" },
      { value: "Seoul", zh: "首爾" },
      { value: "Ulsan", zh: "蔚山" }
    ],
    MY: [
      { value: "Johor", zh: "柔佛" },
      { value: "Kedah", zh: "吉打" },
      { value: "Kelantan", zh: "吉蘭丹" },
      { value: "Kuala Lumpur", zh: "吉隆坡" },
      { value: "Labuan", zh: "納閩" },
      { value: "Malacca", zh: "馬六甲" },
      { value: "Negeri Sembilan", zh: "森美蘭" },
      { value: "Pahang", zh: "彭亨" },
      { value: "Penang", zh: "檳城" },
      { value: "Perak", zh: "霹靂" },
      { value: "Perlis", zh: "玻璃市" },
      { value: "Putrajaya", zh: "布城" },
      { value: "Sabah", zh: "沙巴" },
      { value: "Sarawak", zh: "砂拉越" },
      { value: "Selangor", zh: "雪蘭莪" },
      { value: "Terengganu", zh: "登嘉樓" }
    ],
    TW: [
      { value: "Changhua County", zh: "彰化縣" },
      { value: "Chiayi City", zh: "嘉義市" },
      { value: "Chiayi County", zh: "嘉義縣" },
      { value: "Hsinchu City", zh: "新竹市" },
      { value: "Hsinchu County", zh: "新竹縣" },
      { value: "Hualien County", zh: "花蓮縣" },
      { value: "Kaohsiung City", zh: "高雄市" },
      { value: "Keelung City", zh: "基隆市" },
      { value: "Kinmen County", zh: "金門縣" },
      { value: "Lienchiang County", zh: "連江縣" },
      { value: "Miaoli County", zh: "苗栗縣" },
      { value: "Nantou County", zh: "南投縣" },
      { value: "New Taipei City", zh: "新北市" },
      { value: "Penghu County", zh: "澎湖縣" },
      { value: "Pingtung County", zh: "屏東縣" },
      { value: "Taichung City", zh: "台中市" },
      { value: "Tainan City", zh: "台南市" },
      { value: "Taipei City", zh: "台北市" },
      { value: "Taitung County", zh: "台東縣" },
      { value: "Taoyuan City", zh: "桃園市" },
      { value: "Yilan County", zh: "宜蘭縣" },
      { value: "Yunlin County", zh: "雲林縣" }
    ],
    US: [
      { value: "Alabama", zh: "阿拉巴馬州" },
      { value: "Alaska", zh: "阿拉斯加州" },
      { value: "Arizona", zh: "亞利桑那州" },
      { value: "Arkansas", zh: "阿肯色州" },
      { value: "California", zh: "加州" },
      { value: "Colorado", zh: "科羅拉多州" },
      { value: "Connecticut", zh: "康乃狄克州" },
      { value: "Delaware", zh: "德拉瓦州" },
      { value: "District of Columbia", zh: "哥倫比亞特區" },
      { value: "Florida", zh: "佛州" },
      { value: "Georgia", zh: "喬治亞州" },
      { value: "Hawaii", zh: "夏威夷州" },
      { value: "Idaho", zh: "愛達荷州" },
      { value: "Illinois", zh: "伊利諾州" },
      { value: "Indiana", zh: "印第安納州" },
      { value: "Iowa", zh: "愛荷華州" },
      { value: "Kansas", zh: "堪薩斯州" },
      { value: "Kentucky", zh: "肯塔基州" },
      { value: "Louisiana", zh: "路易斯安那州" },
      { value: "Maine", zh: "緬因州" },
      { value: "Maryland", zh: "馬里蘭州" },
      { value: "Massachusetts", zh: "麻薩諸塞州" },
      { value: "Michigan", zh: "密西根州" },
      { value: "Minnesota", zh: "明尼蘇達州" },
      { value: "Mississippi", zh: "密西西比州" },
      { value: "Missouri", zh: "密蘇里州" },
      { value: "Montana", zh: "蒙大拿州" },
      { value: "Nebraska", zh: "內布拉斯加州" },
      { value: "Nevada", zh: "內華達州" },
      { value: "New Hampshire", zh: "新罕布什爾州" },
      { value: "New Jersey", zh: "新澤西州" },
      { value: "New Mexico", zh: "新墨西哥州" },
      { value: "New York", zh: "紐約州" },
      { value: "North Carolina", zh: "北卡羅來納州" },
      { value: "North Dakota", zh: "北達科他州" },
      { value: "Ohio", zh: "俄亥俄州" },
      { value: "Oklahoma", zh: "奧克拉荷馬州" },
      { value: "Oregon", zh: "俄勒岡州" },
      { value: "Pennsylvania", zh: "賓州" },
      { value: "Rhode Island", zh: "羅德島州" },
      { value: "South Carolina", zh: "南卡羅來納州" },
      { value: "South Dakota", zh: "南達科他州" },
      { value: "Tennessee", zh: "田納西州" },
      { value: "Texas", zh: "德州" },
      { value: "Utah", zh: "猶他州" },
      { value: "Vermont", zh: "佛蒙特州" },
      { value: "Virginia", zh: "維吉尼亞州" },
      { value: "Washington", zh: "華盛頓州" },
      { value: "West Virginia", zh: "西維吉尼亞州" },
      { value: "Wisconsin", zh: "威斯康辛州" },
      { value: "Wyoming", zh: "懷俄明州" }
    ]
  }
};
